name: f1_2021_udp
description: Package for listening Telemetry data from F1 2021 game.
version: 1.0.0
repository: https://github.com/AlfaSquaD/f1_2021_udp
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  logger: ^1.1.0
  meta: ^1.7.0
  path: ^1.8.0
  udp: ^5.0.1

dev_dependencies:
  lints: ^1.0.0
